version: "3.8"
services:
  dd-agent:
    image: datadog/agent:latest
    container_name: dd-agent
    ports:
      - 127.0.0.1:8126:8126/tcp
      - 127.0.0.1:8125:8125/udp
    volumes:
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DD_LOG_LEVEL=TRACE
      - DD_USE_DOGSTATSD=true
      - DD_API_KEY=${DD_API_KEY}
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true